ALTER TABLE orbeon_form_definition ADD COLUMN id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orbeon_form_definition ALTER COLUMN id DROP DEFAULT;
ALTER TABLE orbeon_form_definition ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
ALTER TABLE orbeon_form_definition ADD PRIMARY KEY (id);

ALTER TABLE orbeon_form_definition_attach ADD COLUMN id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orbeon_form_definition_attach ALTER COLUMN id DROP DEFAULT;
ALTER TABLE orbeon_form_definition_attach ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
ALTER TABLE orbeon_form_definition_attach ADD PRIMARY KEY (id);

ALTER TABLE orbeon_form_data_attach ADD COLUMN id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orbeon_form_data_attach ALTER COLUMN id DROP DEFAULT;
ALTER TABLE orbeon_form_data_attach ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
ALTER TABLE orbeon_form_data_attach ADD PRIMARY KEY (id);

ALTER TABLE orbeon_i_current ADD COLUMN id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orbeon_i_current ALTER COLUMN id DROP DEFAULT;
ALTER TABLE orbeon_i_current ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
ALTER TABLE orbeon_i_current ADD PRIMARY KEY (id);

ALTER TABLE orbeon_i_control_text ADD COLUMN id INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orbeon_i_control_text ALTER COLUMN id DROP DEFAULT;
ALTER TABLE orbeon_i_control_text ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
ALTER TABLE orbeon_i_control_text ADD PRIMARY KEY (id);

ALTER TABLE orbeon_organization ADD PRIMARY KEY (id, pos);
