ALTER TABLE orbeon_form_definition ADD id_new NUMBER GENERATED BY DEFAULT AS IDENTITY;
UPDATE orbeon_form_definition SET id_new = orbeon_seq.NEXTVAL;
ALTER TABLE orbeon_form_definition ADD CONSTRAINT orbeon_form_definition_pk PRIMARY KEY (id_new);
ALTER TABLE orbeon_form_definition RENAME COLUMN id_new TO id;

ALTER TABLE orbeon_form_definition_attach ADD id_new NUMBER GENERATED BY DEFAULT AS IDENTITY;
UPDATE orbeon_form_definition_attach SET id_new = orbeon_seq.NEXTVAL;
ALTER TABLE orbeon_form_definition_attach ADD CONSTRAINT orbeon_form_definition_attach_pk PRIMARY KEY (id_new);
ALTER TABLE orbeon_form_definition_attach RENAME COLUMN id_new TO id;

ALTER TABLE orbeon_form_data_attach ADD id_new NUMBER GENERATED BY DEFAULT AS IDENTITY;
UPDATE orbeon_form_data_attach SET id_new = orbeon_seq.NEXTVAL;
ALTER TABLE orbeon_form_data_attach ADD CONSTRAINT orbeon_form_data_attach_pk PRIMARY KEY (id_new);
ALTER TABLE orbeon_form_data_attach RENAME COLUMN id_new TO id;

ALTER TABLE orbeon_i_current ADD id_new NUMBER GENERATED BY DEFAULT AS IDENTITY;
UPDATE orbeon_i_current SET id_new = orbeon_seq.NEXTVAL;
ALTER TABLE orbeon_i_current ADD CONSTRAINT orbeon_i_current_pk PRIMARY KEY (id_new);
ALTER TABLE orbeon_i_current RENAME COLUMN id_new TO id;

ALTER TABLE orbeon_i_control_text ADD id_new NUMBER GENERATED BY DEFAULT AS IDENTITY;
UPDATE orbeon_i_control_text SET id_new = orbeon_seq.NEXTVAL;
ALTER TABLE orbeon_i_control_text ADD CONSTRAINT orbeon_i_control_text_pk PRIMARY KEY (id_new);
ALTER TABLE orbeon_i_control_text RENAME COLUMN id_new TO id;

ALTER TABLE orbeon_organization ADD CONSTRAINT orbeon_organization_pk PRIMARY KEY (id, pos);
