ARG base_image=default

FROM $base_image

RUN mkdir -p /tmp/orbeon_forms
WORKDIR /tmp/orbeon_forms

# JDBC driver for PostgreSQL
RUN wget https://jdbc.postgresql.org/download/postgresql-42.7.3.jar
RUN mv postgresql-42.7.3.jar /opt/jboss/wildfly/standalone/deployments

# Cleanup
RUN rm -rf /tmp/orbeon_forms
