-dontobfuscate
-dontoptimize
-dontnote
-dontwarn

# Keep the main entry point
-keep public class org.orbeon.tools.s3migration.Main {
    public static void main(java.lang.String[]);
}

# Keep resource manager factory (loaded by Class.forName via ResourceManagerWrapper)
-keep class org.orbeon.oxf.resources.ClassLoaderResourceManagerFactory { *; }

# Keep property provider (loaded via ServiceLoader)
-keep class org.orbeon.oxf.properties.ResourcesPropertyProvider { *; }

# Keep JDBC drivers (use reflection for connection properties)
-keep class org.postgresql.** { *; }
-keep class com.mysql.** { *; }
-keep class oracle.** { *; }
-keep class com.ibm.db2.** { *; }
-keep class com.microsoft.sqlserver.** { *; }
-keep class org.sqlite.** { *; }

# AWS SDK uses reflection and service loading
-keep class software.amazon.awssdk.** { *; }

# Apache HTTP Client (used by AWS SDK) and logging (loaded via reflection)
-keep class org.apache.http.** { *; }
-keep class org.apache.commons.logging.** { *; }
-keep class org.apache.logging.** { *; }

# Orbeon Xerces (loaded via reflection by ObjectFactory)
-keep class org.orbeon.apache.xerces.** { *; }

# Keep Serializable support
-keepnames class * implements java.io.Serializable
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
