package org.orbeon.oxf.util

import org.orbeon.datatypes.Mediatype
import org.orbeon.oxf.http.Headers
import org.orbeon.oxf.util.CollectionUtils.combineValues
import org.orbeon.oxf.util.PathUtils.findExtension


object Mediatypes extends MediatypesTrait {

  private case class Mapping(extension: String, mediatype: String, label: String)

  private val AllMappings: List[Mapping] = List(
    Mapping(extension = "bin",      mediatype = "application/octet-stream",                                                   label = "Binary"),
    Mapping(extension = "jpg",      mediatype = "image/jpeg",                                                                 label = "JPEG"),
    Mapping(extension = "jpeg",     mediatype = "image/jpeg",                                                                 label = "JPEG"),
    Mapping(extension = "jpe",      mediatype = "image/jpeg",                                                                 label = "JPEG"),
    Mapping(extension = "png",      mediatype = "image/png",                                                                  label = "PNG"),
    Mapping(extension = "svg",      mediatype = "image/svg+xml",                                                              label = "SVG"),
    Mapping(extension = "svgz",     mediatype = "image/svg+xml",                                                              label = "SVG"),
    Mapping(extension = "tiff",     mediatype = "image/tiff",                                                                 label = "TIFF"),
    Mapping(extension = "tif",      mediatype = "image/tiff",                                                                 label = "TIFF"),
    Mapping(extension = "bmp",      mediatype = "image/bmp",                                                                  label = "BMP"),
    Mapping(extension = "gif",      mediatype = "image/gif",                                                                  label = "GIF"),
    Mapping(extension = "heic",     mediatype = "image/heic",                                                                 label = "HEIC"),
    Mapping(extension = "heif",     mediatype = "image/heif",                                                                 label = "HEIF"),
    Mapping(extension = "webp",     mediatype = "image/webp",                                                                 label = "WebP"),
    Mapping(extension = "ico",      mediatype = "image/vnd.microsoft.icon",                                                   label = "Icon"),
    Mapping(extension = "xhtml",    mediatype = "application/xhtml+xml",                                                      label = "XHTML"),
    Mapping(extension = "mpeg",     mediatype = "video/mpeg",                                                                 label = "MPEG"),
    Mapping(extension = "mpg",      mediatype = "video/mpeg",                                                                 label = "MPEG"),
    Mapping(extension = "mpe",      mediatype = "video/mpeg",                                                                 label = "MPEG"),
    Mapping(extension = "webm",     mediatype = "video/webm",                                                                 label = "WebM"),
    Mapping(extension = "avi",      mediatype = "video/x-msvideo",                                                            label = "AVI"),
    Mapping(extension = "ogv",      mediatype = "video/ogg",                                                                  label = "Ogg"),
    Mapping(extension = "qt",       mediatype = "video/quicktime",                                                            label = "QuickTime"),
    Mapping(extension = "mov",      mediatype = "video/quicktime",                                                            label = "QuickTime"),
    Mapping(extension = "mp4",      mediatype = "video/mp4",                                                                  label = "MP4"),
    Mapping(extension = "wmv",      mediatype = "video/x-ms-wmv",                                                             label = "WMV"),
    Mapping(extension = "aac",      mediatype = "audio/aac",                                                                  label = "AAC"),
    Mapping(extension = "aac",      mediatype = "audio/aac",                                                                  label = "AAC"),
    Mapping(extension = "wav",      mediatype = "audio/wav",                                                                  label = "WAV"),
    Mapping(extension = "mid",      mediatype = "audio/midi",                                                                 label = "MIDI"),
    Mapping(extension = "midi",     mediatype = "audio/midi",                                                                 label = "MIDI"),
    Mapping(extension = "kar",      mediatype = "audio/midi",                                                                 label = "MIDI"),
    Mapping(extension = "mp3",      mediatype = "audio/mpeg",                                                                 label = "MP3"),
    Mapping(extension = "weba",     mediatype = "audio/webm",                                                                 label = "WebM"),
    Mapping(extension = "opus",     mediatype = "audio/opus",                                                                 label = "Opus"),
    Mapping(extension = "oga",      mediatype = "audio/ogg",                                                                  label = "Ogg"),
    Mapping(extension = "ogg",      mediatype = "audio/ogg",                                                                  label = "Ogg"),
    Mapping(extension = "html",     mediatype = "text/html",                                                                  label = "HTML"),
    Mapping(extension = "htm",      mediatype = "text/html",                                                                  label = "HTML"),
    Mapping(extension = "css",      mediatype = "text/css",                                                                   label = "CSS"),
    Mapping(extension = "xml",      mediatype = "application/xml",                                                            label = "XML"),
    Mapping(extension = "xsl",      mediatype = "application/xml",                                                            label = "XML"),
    Mapping(extension = "json",     mediatype = "application/json",                                                           label = "JSON"),
    Mapping(extension = "ps",       mediatype = "application/postscript",                                                     label = "PostScript"),
    Mapping(extension = "ai",       mediatype = "application/postscript",                                                     label = "PostScript"),
    Mapping(extension = "eps",      mediatype = "application/postscript",                                                     label = "PostScript"),
    Mapping(extension = "pdf",      mediatype = "application/pdf",                                                            label = "PDF"),
    Mapping(extension = "rtf",      mediatype = "application/rtf",                                                            label = "RTF"),
    Mapping(extension = "mml",      mediatype = "application/mathml+xml",                                                     label = "MathML"),
    Mapping(extension = "asc",      mediatype = "text/plain",                                                                 label = "Text"),
    Mapping(extension = "txt",      mediatype = "text/plain",                                                                 label = "Text"),
    Mapping(extension = "text",     mediatype = "text/plain",                                                                 label = "Text"),
    Mapping(extension = "diff",     mediatype = "text/plain",                                                                 label = "Text"),
    Mapping(extension = "js",       mediatype = "text/javascript",                                                            label = "JavaScript"),
    Mapping(extension = "mjs",      mediatype = "text/javascript",                                                            label = "JavaScript"),
    Mapping(extension = "zip",      mediatype = "application/zip",                                                            label = "ZIP"),
    Mapping(extension = "7z",       mediatype = "application/x-7z-compressed",                                                label = "7z"),
    Mapping(extension = "tar",      mediatype = "application/x-tar",                                                          label = "TAR"),
    Mapping(extension = "csv",      mediatype = "text/csv",                                                                   label = "CSV"),
    Mapping(extension = "jar",      mediatype = "application/java-archive",                                                   label = "Java"),
    Mapping(extension = "mpkg",     mediatype = "application/vnd.apple.installer+xml",                                        label = "macOS Installer"),
    Mapping(extension = "php",      mediatype = "application/php",                                                            label = "PHP Script"),
    Mapping(extension = "phtml",    mediatype = "application/php",                                                            label = "PHP Script"),
    Mapping(extension = "pht",      mediatype = "application/php",                                                            label = "PHP Script"),
    Mapping(extension = "gz",       mediatype = "application/gzip",                                                           label = "Gzip"),
    Mapping(extension = "rar",      mediatype = "application/vnd.rar",                                                        label = "RAR"),
    Mapping(extension = "bz",       mediatype = "application/x-bzip",                                                         label = "Bzip"),
    Mapping(extension = "bz2",      mediatype = "application/x-bzip2",                                                        label = "Bzip2"),
    Mapping(extension = "sh",       mediatype = "application/x-sh",                                                           label = "Shell Script"),
    Mapping(extension = "csh",      mediatype = "application/x-csh",                                                          label = "C Shell Script"),
    Mapping(extension = "ics",      mediatype = "text/calendar",                                                              label = "iCalendar"),
    Mapping(extension = "swf",      mediatype = "application/x-shockwave-flash",                                              label = "Flash"),
    Mapping(extension = "otf",      mediatype = "font/otf",                                                                   label = "OpenType"),
    Mapping(extension = "sfnt",     mediatype = "font/sfnt",                                                                  label = "SFNT"),
    Mapping(extension = "ttf",      mediatype = "font/ttf",                                                                   label = "TrueType"),
    Mapping(extension = "woff",     mediatype = "application/woff",                                                           label = "WOFF"),
    Mapping(extension = "woff2",    mediatype = "font/woff2",                                                                 label = "WOFF2"),
    Mapping(extension = "eot",      mediatype = "application/vnd.ms-fontobject",                                              label = "EOT"),
    Mapping(extension = "azw",      mediatype = "application/vnd.amazon.ebook",                                               label = "Kindle"),
    Mapping(extension = "epub",     mediatype = "application/epub+zip",                                                       label = "EPUB"),
    Mapping(extension = "odp",      mediatype = "application/vnd.oasis.opendocument.presentation",                            label = "ODP"),
    Mapping(extension = "ods",      mediatype = "application/vnd.oasis.opendocument.spreadsheet",                             label = "ODS"),
    Mapping(extension = "odt",      mediatype = "application/vnd.oasis.opendocument.text",                                    label = "ODT"),
    Mapping(extension = "doc",      mediatype = "application/msword",                                                         label = "Word"),
    Mapping(extension = "dot",      mediatype = "application/msword",                                                         label = "Word"),
    Mapping(extension = "docx",     mediatype = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",    label = "Word"),
    Mapping(extension = "dotx",     mediatype = "application/vnd.openxmlformats-officedocument.wordprocessingml.template",    label = "Word"),
    Mapping(extension = "docm",     mediatype = "application/vnd.ms-word.document.macroenabled.12",                           label = "Word Macro"),
    Mapping(extension = "dotm",     mediatype = "application/vnd.ms-word.template.macroenabled.12",                           label = "Word Macro"),
    Mapping(extension = "xls",      mediatype = "application/vnd.ms-excel",                                                   label = "Excel"),
    Mapping(extension = "xlt",      mediatype = "application/vnd.ms-excel",                                                   label = "Excel"),
    Mapping(extension = "xla",      mediatype = "application/vnd.ms-excel",                                                   label = "Excel"),
    Mapping(extension = "xlsx",     mediatype = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",          label = "Excel"),
    Mapping(extension = "xltx",     mediatype = "application/vnd.openxmlformats-officedocument.spreadsheetml.template",       label = "Excel"),
    Mapping(extension = "xlsm",     mediatype = "application/vnd.ms-excel.sheet.macroenabled.12",                             label = "Excel Macro"),
    Mapping(extension = "xltm",     mediatype = "application/vnd.ms-excel.template.macroenabled.12",                          label = "Excel Macro"),
    Mapping(extension = "xlam",     mediatype = "application/vnd.ms-excel.addin.macroenabled.12",                             label = "Excel Add-in"),
    Mapping(extension = "xlsb",     mediatype = "application/vnd.ms-excel.sheet.binary.macroenabled.12",                      label = "Excel Binary"),
    Mapping(extension = "ppt",      mediatype = "application/vnd.ms-powerpoint",                                              label = "PowerPoint"),
    Mapping(extension = "pot",      mediatype = "application/vnd.ms-powerpoint",                                              label = "PowerPoint"),
    Mapping(extension = "pps",      mediatype = "application/vnd.ms-powerpoint",                                              label = "PowerPoint"),
    Mapping(extension = "ppa",      mediatype = "application/vnd.ms-powerpoint",                                              label = "PowerPoint"),
    Mapping(extension = "pptx",     mediatype = "application/vnd.openxmlformats-officedocument.presentationml.presentation",  label = "PowerPoint"),
    Mapping(extension = "potx",     mediatype = "application/vnd.openxmlformats-officedocument.presentationml.template",      label = "PowerPoint"),
    Mapping(extension = "ppsx",     mediatype = "application/vnd.openxmlformats-officedocument.presentationml.slideshow",     label = "PowerPoint"),
    Mapping(extension = "ppam",     mediatype = "application/vnd.ms-powerpoint.addin.macroenabled.12",                        label = "PowerPoint Add-in"),
    Mapping(extension = "pptm",     mediatype = "application/vnd.ms-powerpoint.presentation.macroenabled.12",                 label = "PowerPoint Macro"),
    Mapping(extension = "potm",     mediatype = "application/vnd.ms-powerpoint.template.macroenabled.12",                     label = "PowerPoint Macro"),
    Mapping(extension = "ppsm",     mediatype = "application/vnd.ms-powerpoint.slideshow.macroenabled.12",                    label = "PowerPoint Macro"),
    Mapping(extension = "msg",      mediatype = "application/vnd.ms-outlook",                                                 label = "Outlook Message"),
    Mapping(extension = "htc",      mediatype = "text/x-component",                                                           label = "HTML"),
    Mapping(extension = "ez",       mediatype = "application/andrew-inset",                                                   label = "Andrew Inset"),
    Mapping(extension = "csm",      mediatype = "application/cu-seeme",                                                       label = "CU-SeeMe"),
    Mapping(extension = "cu",       mediatype = "application/cu-seeme",                                                       label = "CU-SeeMe"),
    Mapping(extension = "tsp",      mediatype = "application/dsptype",                                                        label = "DSP Type"),
    Mapping(extension = "spl",      mediatype = "application/futuresplash",                                                   label = "FutureSplash"),
    Mapping(extension = "cpt",      mediatype = "application/mac-compactpro",                                                 label = "Compact Pro"),
    Mapping(extension = "hqx",      mediatype = "application/mac-binhex40",                                                   label = "BinHex"),
    Mapping(extension = "nb",       mediatype = "application/mathematica",                                                    label = "Mathematica Notebook"),
    Mapping(extension = "mdb",      mediatype = "application/msaccess",                                                       label = "Access Database"),
    Mapping(extension = "oda",      mediatype = "application/oda",                                                            label = "ODA"),
    Mapping(extension = "pgp",      mediatype = "application/pgp-signature",                                                  label = "PGP Signature"),
    Mapping(extension = "smi",      mediatype = "application/smil",                                                           label = "SMIL"),
    Mapping(extension = "smil",     mediatype = "application/smil",                                                           label = "SMIL"),
    Mapping(extension = "sdw",      mediatype = "application/vnd.stardivision.writer",                                        label = "StarWriter"),
    Mapping(extension = "sgl",      mediatype = "application/vnd.stardivision.writer-global",                                 label = "StarWriter Global"),
    Mapping(extension = "vor",      mediatype = "application/vnd.stardivision.writer",                                        label = "StarWriter"),
    Mapping(extension = "sdc",      mediatype = "application/vnd.stardivision.calc",                                          label = "StarCalc"),
    Mapping(extension = "sda",      mediatype = "application/vnd.stardivision.draw",                                          label = "StarDraw Drawing"),
    Mapping(extension = "sdd",      mediatype = "application/vnd.stardivision.impress",                                       label = "StarImpress"),
    Mapping(extension = "sdp",      mediatype = "application/vnd.stardivision.impress-packed",                                label = "StarImpress Packed"),
    Mapping(extension = "smf",      mediatype = "application/vnd.stardivision.math",                                          label = "StarMath Formula"),
    Mapping(extension = "sds",      mediatype = "application/vnd.stardivision.chart",                                         label = "StarChart"),
    Mapping(extension = "smd",      mediatype = "application/vnd.stardivision.mail",                                          label = "StarMail"),
    Mapping(extension = "wp5",      mediatype = "application/wordperfect5.1",                                                 label = "WordPerfect 5.1"),
    Mapping(extension = "wk",       mediatype = "application/x-123",                                                          label = "Lotus 1-2-3"),
    Mapping(extension = "bcpio",    mediatype = "application/x-bcpio",                                                        label = "BCPIO"),
    Mapping(extension = "vcd",      mediatype = "application/x-cdlink",                                                       label = "VCD Link"),
    Mapping(extension = "pgn",      mediatype = "application/x-chess-pgn",                                                    label = "Chess PGN"),
    Mapping(extension = "cpio",     mediatype = "application/x-cpio",                                                         label = "CPIO"),
    Mapping(extension = "csh",      mediatype = "application/x-csh",                                                          label = "C Shell Script"),
    Mapping(extension = "deb",      mediatype = "application/x-debian-package",                                               label = "Debian Package"),
    Mapping(extension = "dcr",      mediatype = "application/x-director",                                                     label = "Director Movie"),
    Mapping(extension = "dir",      mediatype = "application/x-director",                                                     label = "Director Movie"),
    Mapping(extension = "dxr",      mediatype = "application/x-director",                                                     label = "Director Movie"),
    Mapping(extension = "wad",      mediatype = "application/x-doom",                                                         label = "DOOM WAD"),
    Mapping(extension = "dms",      mediatype = "application/x-dms",                                                          label = "Amiga DMS"),
    Mapping(extension = "dvi",      mediatype = "application/x-dvi",                                                          label = "TeX DVI"),
    Mapping(extension = "pfa",      mediatype = "application/x-font",                                                         label = "Generic Font"),
    Mapping(extension = "pfb",      mediatype = "application/x-font",                                                         label = "Generic Font"),
    Mapping(extension = "gsf",      mediatype = "application/x-font",                                                         label = "Generic Font"),
    Mapping(extension = "pcf",      mediatype = "application/x-font",                                                         label = "Generic Font"),
    Mapping(extension = "z",        mediatype = "application/x-font",                                                         label = "Generic Font"),
    Mapping(extension = "spl",      mediatype = "application/x-futuresplash",                                                 label = "FutureSplash"),
    Mapping(extension = "gnumeric", mediatype = "application/x-gnumeric",                                                     label = "Gnumeric"),
    Mapping(extension = "gtar",     mediatype = "application/x-gtar",                                                         label = "GNU Tar"),
    Mapping(extension = "tgz",      mediatype = "application/x-gtar",                                                         label = "GNU Tar"),
    Mapping(extension = "taz",      mediatype = "application/x-gtar",                                                         label = "GNU Tar"),
    Mapping(extension = "hdf",      mediatype = "application/x-hdf",                                                          label = "HDF Data"),
    Mapping(extension = "phps",     mediatype = "application/x-httpd-php-source",                                             label = "PHP Source"),
    Mapping(extension = "php3",     mediatype = "application/x-httpd-php3",                                                   label = "PHP3 Script"),
    Mapping(extension = "php3p",    mediatype = "application/x-httpd-php3-preprocessed",                                      label = "PHP3 Preprocessed"),
    Mapping(extension = "php4",     mediatype = "application/x-httpd-php4",                                                   label = "PHP4 Script"),
    Mapping(extension = "ica",      mediatype = "application/x-ica",                                                          label = "ICA"),
    Mapping(extension = "jnlp",     mediatype = "application/x-java-jnlp-file",                                               label = "JNLP"),
    Mapping(extension = "ser",      mediatype = "application/x-java-serialized-object",                                       label = "Serialized Object"),
    Mapping(extension = "class",    mediatype = "application/x-java-vm",                                                      label = "Java Class"),
    Mapping(extension = "chrt",     mediatype = "application/x-kchart",                                                       label = "KChart"),
    Mapping(extension = "kil",      mediatype = "application/x-killustrator",                                                 label = "KIllustrator Drawing"),
    Mapping(extension = "kpr",      mediatype = "application/x-kpresenter",                                                   label = "KPresenter"),
    Mapping(extension = "kpt",      mediatype = "application/x-kpresenter",                                                   label = "KPresenter"),
    Mapping(extension = "skp",      mediatype = "application/x-koan",                                                         label = "Koan Music"),
    Mapping(extension = "skd",      mediatype = "application/x-koan",                                                         label = "Koan Music"),
    Mapping(extension = "skt",      mediatype = "application/x-koan",                                                         label = "Koan Music"),
    Mapping(extension = "skm",      mediatype = "application/x-koan",                                                         label = "Koan Music"),
    Mapping(extension = "ksp",      mediatype = "application/x-kspread",                                                      label = "KSpread"),
    Mapping(extension = "kwd",      mediatype = "application/x-kword",                                                        label = "KWord"),
    Mapping(extension = "kwt",      mediatype = "application/x-kword",                                                        label = "KWord"),
    Mapping(extension = "latex",    mediatype = "application/x-latex",                                                        label = "LaTeX"),
    Mapping(extension = "lha",      mediatype = "application/x-lha",                                                          label = "LHA"),
    Mapping(extension = "lzh",      mediatype = "application/x-lzh",                                                          label = "LZH"),
    Mapping(extension = "lzx",      mediatype = "application/x-lzx",                                                          label = "LZX"),
    Mapping(extension = "frm",      mediatype = "application/x-maker",                                                        label = "FrameMaker"),
    Mapping(extension = "maker",    mediatype = "application/x-maker",                                                        label = "FrameMaker"),
    Mapping(extension = "frame",   mediatype = "application/x-maker",                                                         label = "FrameMaker"),
    Mapping(extension = "fm",      mediatype = "application/x-maker",                                                         label = "FrameMaker"),
    Mapping(extension = "fb",      mediatype = "application/x-maker",                                                         label = "FrameMaker"),
    Mapping(extension = "book",    mediatype = "application/x-maker",                                                         label = "FrameMaker"),
    Mapping(extension = "fbdoc",   mediatype = "application/x-maker",                                                         label = "FrameMaker"),
    Mapping(extension = "mif",     mediatype = "application/x-mif",                                                           label = "FrameMaker MIF"),
    Mapping(extension = "com",     mediatype = "application/x-msdos-program",                                                 label = "Windows Executable"),
    Mapping(extension = "exe",     mediatype = "application/x-msdos-program",                                                 label = "Windows Executable"),
    Mapping(extension = "bat",     mediatype = "application/x-msdos-program",                                                 label = "Windows Executable"),
    Mapping(extension = "dll",     mediatype = "application/x-msdos-program",                                                 label = "Windows Executable"),
    Mapping(extension = "msi",     mediatype = "application/x-msi",                                                           label = "Windows Installer"),
    Mapping(extension = "nc",      mediatype = "application/x-netcdf",                                                        label = "NetCDF Data"),
    Mapping(extension = "cdf",     mediatype = "application/x-netcdf",                                                        label = "NetCDF Data"),
    Mapping(extension = "pac",     mediatype = "application/x-ns-proxy-autoconfig",                                           label = "Proxy Auto-Config"),
    Mapping(extension = "o",       mediatype = "application/x-object",                                                        label = "Object"),
    Mapping(extension = "oza",     mediatype = "application/x-oz-application",                                                label = "OZ Application"),
    Mapping(extension = "pl",      mediatype = "application/x-perl",                                                          label = "Perl Script"),
    Mapping(extension = "pm",      mediatype = "application/x-perl",                                                          label = "Perl Script"),
    Mapping(extension = "crl",     mediatype = "application/x-pkcs7-crl",                                                     label = "Certificate Revocation List"),
    Mapping(extension = "rpm",     mediatype = "application/x-redhat-package-manager",                                        label = "RPM Package"),
    Mapping(extension = "shar",    mediatype = "application/x-shar",                                                          label = "Shell"),
    Mapping(extension = "sit",     mediatype = "application/x-stuffit",                                                       label = "StuffIt"),
    Mapping(extension = "sv4cpio", mediatype = "application/x-sv4cpio",                                                       label = "SV4 CPIO"),
    Mapping(extension = "sv4crc",  mediatype = "application/x-sv4crc",                                                        label = "SV4 CRC"),
    Mapping(extension = "tcl",     mediatype = "application/x-tcl",                                                           label = "Tcl Script"),
    Mapping(extension = "tex",     mediatype = "application/x-tex",                                                           label = "TeX"),
    Mapping(extension = "gf",      mediatype = "application/x-tex-gf",                                                        label = "TeX GF"),
    Mapping(extension = "pk",      mediatype = "application/x-tex-pk",                                                        label = "TeX PK"),
    Mapping(extension = "texinfo", mediatype = "application/x-texinfo",                                                       label = "Texinfo"),
    Mapping(extension = "texi",    mediatype = "application/x-texinfo",                                                       label = "Texinfo"),
    Mapping(extension = "bak",     mediatype = "application/x-trash",                                                         label = "Backup"),
    Mapping(extension = "old",     mediatype = "application/x-trash",                                                         label = "Backup"),
    Mapping(extension = "sik",     mediatype = "application/x-trash",                                                         label = "Backup"),
    Mapping(extension = "t",       mediatype = "application/x-troff",                                                         label = "Troff"),
    Mapping(extension = "tr",      mediatype = "application/x-troff",                                                         label = "Troff"),
    Mapping(extension = "roff",    mediatype = "application/x-troff",                                                         label = "Troff"),
    Mapping(extension = "man",     mediatype = "application/x-troff-man",                                                     label = "Man Page"),
    Mapping(extension = "me",      mediatype = "application/x-troff-me",                                                      label = "Troff ME"),
    Mapping(extension = "ms",      mediatype = "application/x-troff-ms",                                                      label = "Troff MS"),
    Mapping(extension = "ustar",   mediatype = "application/x-ustar",                                                         label = "USTAR"),
    Mapping(extension = "src",     mediatype = "application/x-wais-source",                                                   label = "WAIS Source"),
    Mapping(extension = "wz",      mediatype = "application/x-wingz",                                                         label = "Wingz"),
    Mapping(extension = "crt",     mediatype = "application/x-x509-ca-cert",                                                  label = "CA Certificate"),
    Mapping(extension = "fig",     mediatype = "application/x-xfig",                                                          label = "Xfig Drawing"),
    Mapping(extension = "au",      mediatype = "audio/basic",                                                                 label = "AU"),
    Mapping(extension = "snd",     mediatype = "audio/basic",                                                                 label = "AU"),
    Mapping(extension = "m3u",     mediatype = "audio/mpegurl",                                                               label = "M3U Playlist"),
    Mapping(extension = "aif",     mediatype = "audio/x-aiff",                                                                label = "AIFF"),
    Mapping(extension = "aiff",    mediatype = "audio/x-aiff",                                                                label = "AIFF"),
    Mapping(extension = "aifc",    mediatype = "audio/x-aiff",                                                                label = "AIFF"),
    Mapping(extension = "gsm",     mediatype = "audio/x-gsm",                                                                 label = "GSM"),
    Mapping(extension = "m3u",     mediatype = "audio/x-mpegurl",                                                             label = "M3U Playlist"),
    Mapping(extension = "rpm",     mediatype = "audio/x-pn-realaudio-plugin",                                                 label = "RealAudio Plugin"),
    Mapping(extension = "ra",      mediatype = "audio/x-pn-realaudio",                                                        label = "RealAudio"),
    Mapping(extension = "rm",      mediatype = "audio/x-pn-realaudio",                                                        label = "RealAudio"),
    Mapping(extension = "ram",     mediatype = "audio/x-pn-realaudio",                                                        label = "RealAudio"),
    Mapping(extension = "ra",      mediatype = "audio/x-realaudio",                                                           label = "RealAudio"),
    Mapping(extension = "pls",     mediatype = "audio/x-scpls",                                                               label = "PLS Playlist"),
    Mapping(extension = "pdb",     mediatype = "chemical/x-pdb",                                                              label = "PDB Chemical"),
    Mapping(extension = "xyz",     mediatype = "chemical/x-xyz",                                                              label = "XYZ Chemical"),
    Mapping(extension = "ief",     mediatype = "image/ief",                                                                   label = "IEF"),
    Mapping(extension = "pcx",     mediatype = "image/pcx",                                                                   label = "PCX"),
    Mapping(extension = "ras",     mediatype = "image/x-cmu-raster",                                                          label = "CMU Raster"),
    Mapping(extension = "cdr",     mediatype = "image/x-coreldraw",                                                           label = "CorelDRAW"),
    Mapping(extension = "pat",     mediatype = "image/x-coreldrawpattern",                                                    label = "Corel Pattern"),
    Mapping(extension = "cdt",     mediatype = "image/x-coreldrawtemplate",                                                   label = "Corel"),
    Mapping(extension = "cpt",     mediatype = "image/x-corelphotopaint",                                                     label = "Corel Photo-Paint"),
    Mapping(extension = "djvu",    mediatype = "image/x-djvu",                                                                label = "DjVu"),
    Mapping(extension = "djv",     mediatype = "image/x-djvu",                                                                label = "DjVu"),
    Mapping(extension = "jng",     mediatype = "image/x-jng",                                                                 label = "JNG"),
    Mapping(extension = "bmp",     mediatype = "image/x-ms-bmp",                                                              label = "BMP"),
    Mapping(extension = "pnm",     mediatype = "image/x-portable-anymap",                                                     label = "PNM"),
    Mapping(extension = "pbm",     mediatype = "image/x-portable-bitmap",                                                     label = "PBM"),
    Mapping(extension = "pgm",     mediatype = "image/x-portable-graymap",                                                    label = "PGM"),
    Mapping(extension = "ppm",     mediatype = "image/x-portable-pixmap",                                                     label = "PPM"),
    Mapping(extension = "rgb",     mediatype = "image/x-rgb",                                                                 label = "RGB"),
    Mapping(extension = "xbm",     mediatype = "image/x-xbitmap",                                                             label = "XBM"),
    Mapping(extension = "xpm",     mediatype = "image/x-xpixmap",                                                             label = "XPM"),
    Mapping(extension = "xwd",     mediatype = "image/x-xwindowdump",                                                         label = "XWD"),
    Mapping(extension = "igs",     mediatype = "model/iges",                                                                  label = "IGES Model"),
    Mapping(extension = "iges",    mediatype = "model/iges",                                                                  label = "IGES Model"),
    Mapping(extension = "msh",     mediatype = "model/mesh",                                                                  label = "Mesh Model"),
    Mapping(extension = "mesh",    mediatype = "model/mesh",                                                                  label = "Mesh Model"),
    Mapping(extension = "silo",    mediatype = "model/mesh",                                                                  label = "Mesh Model"),
    Mapping(extension = "wrl",     mediatype = "model/vrml",                                                                  label = "VRML Model"),
    Mapping(extension = "vrml",    mediatype = "model/vrml",                                                                  label = "VRML Model"),
    Mapping(extension = "rtx",     mediatype = "text/richtext",                                                               label = "Rich Text"),
    Mapping(extension = "tsv",     mediatype = "text/tab-separated-values",                                                   label = "TSV"),
    Mapping(extension = "hdr",     mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "h",       mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "hpp",     mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "hxx",     mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "hh",      mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "src",     mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "c",       mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "cpp",     mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "cxx",     mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "cc",      mediatype = "text/x-c",                                                                    label = "C Source"),
    Mapping(extension = "h",       mediatype = "text/x-chdr",                                                                 label = "C Header"),
    Mapping(extension = "csh",     mediatype = "text/x-csh",                                                                  label = "C Shell Script"),
    Mapping(extension = "c",       mediatype = "text/x-csrc",                                                                 label = "C Source"),
    Mapping(extension = "java",    mediatype = "text/x-java",                                                                 label = "Java Source"),
    Mapping(extension = "moc",     mediatype = "text/x-moc",                                                                  label = "Qt Meta-Object"),
    Mapping(extension = "p",       mediatype = "text/x-pascal",                                                               label = "Pascal Source"),
    Mapping(extension = "pas",     mediatype = "text/x-pascal",                                                               label = "Pascal Source"),
    Mapping(extension = "etx",     mediatype = "text/x-setext",                                                               label = "Setext"),
    Mapping(extension = "sh",      mediatype = "text/x-sh",                                                                   label = "Shell Script"),
    Mapping(extension = "tcl",     mediatype = "text/x-tcl",                                                                  label = "Tcl Script"),
    Mapping(extension = "tk",      mediatype = "text/x-tcl",                                                                  label = "Tcl Script"),
    Mapping(extension = "tex",     mediatype = "text/x-tex",                                                                  label = "TeX"),
    Mapping(extension = "ltx",     mediatype = "text/x-tex",                                                                  label = "TeX"),
    Mapping(extension = "sty",     mediatype = "text/x-tex",                                                                  label = "TeX"),
    Mapping(extension = "cls",     mediatype = "text/x-tex",                                                                  label = "TeX"),
    Mapping(extension = "vcs",     mediatype = "text/x-vcalendar",                                                            label = "vCalendar"),
    Mapping(extension = "vcf",     mediatype = "text/x-vcard",                                                                label = "vCard"),
    Mapping(extension = "dl",      mediatype = "video/dl",                                                                    label = "DL"),
    Mapping(extension = "fli",     mediatype = "video/fli",                                                                   label = "FLI"),
    Mapping(extension = "gl",      mediatype = "video/gl",                                                                    label = "GL"),
    Mapping(extension = "mxu",     mediatype = "video/vnd.mpegurl",                                                           label = "MPEG URL"),
    Mapping(extension = "mng",     mediatype = "video/x-mng",                                                                 label = "MNG"),
    Mapping(extension = "asf",     mediatype = "video/x-ms-asf",                                                              label = "ASF"),
    Mapping(extension = "asx",     mediatype = "video/x-ms-asf",                                                              label = "ASF"),
    Mapping(extension = "movie",   mediatype = "video/x-sgi-movie",                                                           label = "SGI Movie"),
    Mapping(extension = "ice",     mediatype = "x-conference/x-cooltalk",                                                     label = "CoolTalk Session"),
    Mapping(extension = "vrm",     mediatype = "x-world/x-vrml",                                                              label = "VRML World"),
    Mapping(extension = "vrml",    mediatype = "x-world/x-vrml",                                                              label = "VRML World"),
    Mapping(extension = "wrl",     mediatype = "x-world/x-vrml",                                                              label = "VRML World"),
    Mapping(extension = "wbxml",   mediatype = "application/vnd.wap.wbxml",                                                   label = "WAP Binary XML"),
    Mapping(extension = "wmlc",    mediatype = "application/vnd.wap.wmlc",                                                    label = "WAP WMLC"),
    Mapping(extension = "wmlsc",   mediatype = "application/vnd.wap.wmlscriptc",                                              label = "WAP WMLS"),
    Mapping(extension = "wbmp",    mediatype = "image/vnd.wap.wbmp",                                                          label = "WAP Bitmap"),
    Mapping(extension = "wml",     mediatype = "text/vnd.wap.wml",                                                            label = "WAP WML"),
    Mapping(extension = "wmls",    mediatype = "text/vnd.wap.wmlscript",                                                      label = "WAP WMLS"),
  )

  private val (
    mappingsByMediatype: Map[String, List[Mapping]],
    mappingsByExtension: Map[String, List[Mapping]],
    labelsByMediatype  : Map[String, String]
  ) = {

    val mappingsByMediatype = combineValues[String, Mapping, List](AllMappings map { case m @ Mapping(_, mediatype, _)     => mediatype   -> m     }).toMap
    val mappingsByExtension = combineValues[String, Mapping, List](AllMappings map { case m @ Mapping(_, _, _)             => m.extension -> m     }).toMap
    val labelsByMediatype   =                                      AllMappings.map { case     Mapping(_, mediatype, label) => mediatype   -> label } .toMap

    (mappingsByMediatype, mappingsByExtension, labelsByMediatype)
  }

  def findMediatypeForExtension(extension: String): Option[String] =
    for {
      mappings <- mappingsByExtension.get(extension.toLowerCase)
      mapping  <- mappings.headOption
    } yield
      mapping.mediatype

  def findMediatypeForPath(path: String): Option[String] =
    for {
      extension <- findExtension(path.toLowerCase)
      mediatype <- findMediatypeForExtension(extension)
    } yield
      mediatype

  def findMediatypeForPathJava(path: String): String =
    findMediatypeForPath(path).orNull

  def findExtensionForMediatype(mediatype: String): Option[String] =
    for {
      mappings  <- mappingsByMediatype.get(mediatype)
      mapping   <- mappings.headOption
    } yield
      mapping.extension

  def findLabelForMediatype(mediatype: String): Option[String] =
    labelsByMediatype.get(mediatype)

  def getExtensionForMediatypeOrThrow(mediatype: String): String =
    findExtensionForMediatype(mediatype).getOrElse(throw new IllegalArgumentException("mediatype"))

  def fromHeadersOrFilename(
    header  : String => Option[String],
    filename: => Option[String]
  ): Option[Mediatype] = {

    def fromHeaders =
      header(Headers.ContentType)            flatMap
        ContentTypes.getContentTypeMediaType filterNot
        (_ == ContentTypes.OctetStreamContentType)

    def fromFilename =
      filename flatMap findMediatypeForPath

    fromHeaders orElse fromFilename flatMap Mediatype.unapply
  }
}
